query diningCourts($date: Date!) {
  diningCourts {
    name
    latitude
    longitude
    category
    dailyMenu(date: $date) {
      meals {
        name
        type
        startTime
        endTime
      }
    }
  }
}
