query getMenu($location: String!, $date: Date!) {
  diningCourtByName(name: $location) {
    dailyMenu(date: $date) {
      meals {
        startTime
        endTime
        stations {
          items {
            components {
              item {
                name
                nutritionFacts {
                  name
                  label
                  value
                }
              }
            }
            item {
              name
              nutritionFacts {
                name
                label
                value
              }
            }
          }
        }
      }
    }
  }
}
